blank_issues_enabled: false
contact_links:
  - name: Moat Systems support
    url: https://moatsystems.com/contact/
    about: |
      Please only file issues here that you believe represent actual bugs or feature requests for the MLS API PHP Library.
      If you're having general trouble with your MLS API integration, please reach out to support.